### ISSUE TITLE
Trådfri lm1000 Works just fine?

### ISSUE THREAD

**Issue by Kennybarroz** [edvaldeysteinsson/IKEA-Tradfri#8] opened 2019-08-18 15:23 UTC
Hi Edvald! 
These LM1000 bulbs is a temperature bulb. it can change from 2404k to 4000k 
There is no issues what so ever with the Smartthings classic app and Google Home. But with the new Smartthings app the color temperature settings is all wrong, showing wrong kelvin and can only be changed once and second attempt it will crash. 

Please get back to me if you need any more input on this. thanks!

**Comment by edvaldeysteinsson** [comment] 2019-09-01 09:02
Can you post a link to a product page for that bulb so i can read the specs for it?
If the issue is just the min/max color values that are wrong then try changing the min/max color temperature values in the settings for the DTH

**Comment by edvaldeysteinsson** [comment] 2019-09-02 19:34
Just re-read this issue and saw that you were talking about the new smartthings app. I haven't used the new app that much, i prefer the classic but I'm guessing that some changes have to be made to the device type handlers.

**Comment by Kennybarroz** [comment] 2019-09-03 05:42
Hi again! Sorry for the late reply!
The ikea bulb im referring to has artnr: 604.084.83

Im not a pro in coding, i have tried changing the values that i think will do the trick for the bulbs spectrum, but it seems like im not changing the correct values. 

I also noticed that the 004.086.12 (Color trådfri bulb) is not as smooth and color correct as it might intended to be? When changing colors its almost like a switch rather then the other bulbs that dim into colors/mood. 

Is this something you can look into? I can provide more info if you want.

**Comment by edvaldeysteinsson** [comment] 2019-09-03 08:01
The color bulbs are not supported by this DTH, if you assign this DTH tp those they will be treated as white spectrum bulbs and theµ might behave differently. If you have those you should just use the build in RGB / RGBW DTH's and as far as supporting the new app i might look in to it sometime in the future but it's low on my agenda since i don't use that app. Anyone that does and knows coding are welcome to do a PR with a fix

**Closed as completed** 2023-04-05 17:55 UTC
